version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: echo
          command: echo "hello circleci"

workflows:
  sample: 
    jobs:
      - build-and-test