# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0
jobs:
  test:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: echo "hello circleci"
workflows:
  version: 2.0
  test-hello:
    jobs:
      - test
